version: '1'

services:
  backend-fastify:
    container_name: 'test-backend2'
    build:
      context: .
    ports:
      - "5002:5002"
    volumes:
      - ./src:/src
    environment:
      POSTGRES_PORT: ${POSTGRES_PORT}
      POSTGRES_USERNAME: ${POSTGRES_USERNAME}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_HOST: ${POSTGRES_HOST}
      POSTGRES_DATABASE: ${POSTGRES_DATABASE}
      POSTGRES_HOST_REPLICA1: ${POSTGRES_HOST_REPLICA1}
      PORT: ${PORT}
    networks:
      - test-backend-docker_my-network

networks:
  test-backend-docker_my-network:
    external: true